sudo: required
services:
  - docker
before_install:
  - docker build -t raman162/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run raman162/react-test npm test -- --coverage

after_success:
  - echo -E "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker build -t raman162/complex-client ./client
  - docker build -t raman162/complex-nginx ./nginx
  - docker build -t raman162/complex-server ./server
  - docker build -t raman162/complex-worker ./worker
  - docker push raman162/complex-client
  - docker push raman162/complex-server
  - docker push raman162/complex-nginx
  - docker push raman162/complex-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: complex-docker
  environment: ComplexDocker-env
  bucket_name: elasticbeanstalk-us-east-2-340927681771
  bucket_path: complex-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
